---
- name: Enhanced Demo Playbook for AAP Testing
  hosts: all
  gather_facts: yes
  become: true

  vars:
    demo_file: /tmp/demo_aap.txt
    demo_message: "Hello from Ansible! This playbook ran successfully on {{ ansible_hostname }}."
    demo_dir: /tmp/aap_demo_dir
    demo_user: demo_user

  tasks:
    - name: Show basic system facts
      debug:
        msg:
          - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Hostname: {{ ansible_hostname }}"
          - "Kernel: {{ ansible_kernel }}"

    - name: Ensure demo user exists
      user:
        name: "{{ demo_user }}"
        state: present
        shell: /bin/bash

    - name: Create a demo directory
      file:
        path: "{{ demo_dir }}"
        state: directory
        owner: "{{ demo_user }}"
        mode: '0755'

    - name: Create a demo file
      copy:
        dest: "{{ demo_file }}"
        content: "{{ demo_message }}\n"
        owner: "{{ demo_user }}"
        mode: '0644'

    - name: Install some useful test packages
      package:
        name:
          - tree
          - htop
          - curl
        state: present

    - name: Create a simple MOTD banner
      lineinfile:
        path: /etc/motd
        line: "Welcome! Ansible AAP demo ran on {{ ansible_date_time.date }}."
        create: yes

    - name: Run a simple shell command (list /tmp)
      command: ls -l /tmp
      register: tmp_contents

    - name: Show results of /tmp directory listing
      debug:
        var: tmp_contents.stdout_lines

    - name: Print final confirmation message
      debug:
        msg: "✅ Demo playbook completed successfully on {{ ansible_hostname }}!"
